# Generated by Django 3.1.5 on 2026-09-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0053_alphanumeric_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='resume_link',
            field=models.URLField(blank=True, help_text='Shared Google Drive link to the resume', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='resume_link',
            field=models.URLField(blank=True, help_text='Shared Google Drive link to the resume', max_length=500, null=True),
        ),
    ]
