# Generated by Django 3.1.5 on 2026-09-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0054_student_resume_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
