# Generated by Django 3.1.5 on 2026-09-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0055_student_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date of joining, shown on the assistantship sheet', null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date of joining, shown on the assistantship sheet', null=True),
        ),
    ]
