# Generated by Django 3.1.5 on 2026-04-30 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0006_auto_20260304_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sector', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('placement', 'Placement'), ('internship', 'Internship')], default='placement', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('eligible_batches', models.JSONField(default=list)),
                ('eligible_programmes', models.JSONField(default=list)),
                ('eligible_disciplines', models.JSONField(default=list)),
                ('min_cpi', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='placement_cell.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('placed', 'Placed'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement_cell.jobpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_applications', to='globals.extrainfo')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job_post', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PlacementStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.CharField(max_length=10, unique=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_placed', models.PositiveIntegerField(default=0)),
                ('total_companies', models.PositiveIntegerField(default=0)),
                ('avg_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('highest_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Placement Statistics',
                'ordering': ['-batch_year'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlacementProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('is_placed', models.BooleanField(default=False)),
                ('opted_out', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_profile', to='globals.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=100)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('scheduled_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='placement_cell.jobpost')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='PlacementResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField()),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('ctc_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_letter', models.FileField(blank=True, upload_to='placement/offer_letters/')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='placement_cell.placementapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-posted_at'],
            },
        ),
    ]
