# Generated by Django 3.1.5 on 2026-04-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0006_auto_20260304_0836'),
        ('placement_cell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('placement', 'Placement'), ('internship', 'Internship'), ('ppo', 'Pre Placement Offer')], default='placement', max_length=20),
        ),
        migrations.CreateModel(
            name='OffCampusPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=200)),
                ('offer_type', models.CharField(choices=[('placement', 'Placement'), ('internship', 'Internship')], default='placement', max_length=20)),
                ('ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_offcampus_placements', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offcampus_placements', to='globals.extrainfo')),
            ],
            options={
                'ordering': ['-offer_date'],
            },
        ),
    ]
