# Generated by Django 3.1.5 on 2026-04-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0002_auto_20260430_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='apply_link',
            field=models.URLField(blank=True),
        ),
    ]
